### ISSUE TITLE
Possiblity of including commonly used easing functions

### ISSUE THREAD

**Issue by marcoms** [jaxgeller/tweezer.js#2]
I (and I suspect many others) have no idea how the logic works for an easing function and wouldn't be able to construct one in JS! Would it be possible to include a set of common easing functions  (-quart functions would be a good start IMO) in this project, which the user could import if they wanted?

**Comment by jaxgeller** [comment]
@marcoms thanks for the issue, in order to keep this library lightweight I will not be including easings. However, this library conforms to the Robert Penner easing spec that can be found [here](http://gsgd.co.uk/sandbox/jquery/easing/jquery.easing.1.3.js), or for a nice visualization of those you can view that [here](http://easings.net/).

I have also crafted a library called [ez.js](https://github.com/jaxgeller/ez.js) which transforms the easings above into an importable ES6 library. This library works well with Tweezer. For example,

``` es6
// to import one easing
import {easeInCubic} from 'ez.js';
import Tweezer from 'tweezer.js'

new Tweezer({
  start: 0,
  end: 1000,
  easing: easeInCubic
})
```

``` es6
// to import all easings
import * as ez from "ez.js"
import Tweezer from 'tweezer.js'

new Tweezer({
  start: 0,
  end: 1000,
  easing: ez. easeInCirc
})
```

**Comment by marcoms** [comment]
Oh nice, ez.js seems like what I'm looking for!
